_target_: chemtorch.components.data_pipeline.data_splitter.ScaffoldSplitter
train_ratio: 0.8
val_ratio: 0.1
test_ratio: 0.1

split_on: null # reactant or product
mol_idx: null # integer index
include_chirality: false # include chirality in the scaffold smiles

save_path: null 
