_target_: chemtorch.core.routine.SupervisedRoutine
_partial_: true     # Model passed at runtime
_convert_: object   # Convert DictConfig objects to regular Python objects (otherwise the dicts passed to MetricCollection will not work correctly)

defaults:
  - loss: cross_entropy
  - optimizer: adamw
  - lr_scheduler: graphgps_cosine_with_warmup

metrics:
  _target_: torchmetrics.Accuracy
  task: multiclass
  num_classes: ${num_classes}
