_target_: chemtorch.core.routine.RegressionRoutine
_partial_: true     # Model passed at runtime
_convert_: object   # Convert DictConfig objects to regular Python objects (otherwise the dicts passed to MetricCollection will not work correctly)

defaults:
  - loss: mse
  - optimizer: adamw
  - lr_scheduler: cosine_with_warmup

standardizer:
  _target_: chemtorch.utils.Standardizer
  mean: ${mean}   # root config updated with dataset properties at runtime
  std: ${std}     # root config updated with dataset properties at runtime

metrics:
  train:
    _target_: torchmetrics.MetricCollection
    metrics:
      rmse:  
        _target_: torchmetrics.MeanSquaredError
        squared: false
  val: 
    _target_: torchmetrics.MetricCollection
    metrics:
      rmse:  
        _target_: torchmetrics.MeanSquaredError
        squared: false
  test: 
    _target_: torchmetrics.MetricCollection
    metrics:
      rmse:  
        _target_: torchmetrics.MeanSquaredError
        squared: false
      mae:
        _target_: torchmetrics.MeanAbsoluteError