_target_: chemtorch.components.data_pipeline.SimpleDataPipeline

defaults:
  - data_source: single_csv_source
  - column_mapper: column_filter_and_rename
  - data_splitter: index_splitter

data_source:
  data_path: "data/rdb7/barriers/forward_reverse_spiekermann_splits/data.csv"

column_mapper:
  smiles: "rxn_smiles"
  label: "ea"

data_splitter:
  split_index_path: "data/rdb7/barriers/forward_reverse_spiekermann_splits/seed0.pkl"
