_target_: chemtorch.components.data_pipeline.SimpleDataPipeline

defaults:
  - data_source: single_csv_source
  - column_mapper: column_filter_and_rename
  - data_splitter: ratio_splitter

data_source:
  data_path: "data/rgd1/barriers/data.csv"

column_mapper:
  smiles: "smiles"
  label: "ea"

data_splitter:
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
