_target_: chemtorch.components.data_pipeline.SimpleDataPipeline

defaults:
  - data_source: pre_split_csv
  - column_mapper: column_filter_and_rename
  - data_splitter: null

data_source:
  data_folder: "data/uspto-1k/classes/pre_split"
  
column_mapper:
  smiles: "reaction"
  label: "labels"
