_target_: chemtorch.featurizer.FeaturizerCompose

featurizers:
  - _target_: chemtorch.featurizer.BondTypeFeaturizer
  - _target_: chemtorch.featurizer.BondIsConjugatedFeaturizer
  - _target_: chemtorch.featurizer.BondInRingFeaturizer
