_target_: chemtorch.components.representation.graph.featurizer.FeaturizerCompose

featurizers:
  - _target_: chemtorch.components.representation.graph.featurizer.BondTypeFeaturizer
  - _target_: chemtorch.components.representation.graph.featurizer.BondIsConjugatedFeaturizer
  - _target_: chemtorch.components.representation.graph.featurizer.BondInRingFeaturizer
