_target_: chemtorch.components.preprocessing.featurizer.FeaturizerCompose

featurizers:
  - _target_: chemtorch.components.preprocessing.featurizer.BondTypeFeaturizer
  - _target_: chemtorch.components.preprocessing.featurizer.BondIsConjugatedFeaturizer
  - _target_: chemtorch.components.preprocessing.featurizer.BondInRingFeaturizer
