_target_: chemtorch.components.data_pipeline.data_splitter.ScaffoldSplitter
train_ratio: null
val_ratio: null
test_ratio: null

split_on: null # reactant or product
mol_idx: null # integer index
include_chirality: false # include chirality in the scaffold smiles

save_path: null 
