_target_: chemtorch.components.data_pipeline.data_splitter.ScaffoldSplitter
train_ratio: null
val_ratio: null
test_ratio: null

split_on: null # reactant or product
mol_idx: null # first, last, or an integer index
include_chirality: false # include chirality in the scaffold smiles

save_split_dir: null 
save_indices: false
save_csv: false
