_target_: chemtorch.components.representation.graph.featurizer.FeaturizerCompose

featurizers:
  - _target_: chemtorch.components.representation.graph.featurizer.OrganicAtomicNumberOneHotFeaturizer
  - _target_: chemtorch.components.representation.graph.featurizer.AtomDegreeFeaturizer
  - _target_: chemtorch.components.representation.graph.featurizer.AtomFormalChargeFeaturizer
  - _target_: chemtorch.components.representation.graph.featurizer.AtomHCountFeaturizer
  - _target_: chemtorch.components.representation.graph.featurizer.AtomHybridizationFeaturizer
  - _target_: chemtorch.components.representation.graph.featurizer.AtomIsAromaticFeaturizer
  - _target_: chemtorch.components.representation.graph.featurizer.CentiAtomMassFeaturizer
  - _target_: chemtorch.components.representation.graph.featurizer.AtomIsInRingFeaturizer
