_target_: chemtorch.dataset.token_dataset.TokenDataset
_partial_: true

defaults:
  - representation: simple_token
  - transform: null
  
precompute_all: true
cache: true
max_size_cache: null
subsample: null         
