_target_: chemtorch.components.dataset.token_dataset.TokenDataset
_partial_: true

defaults:
  - representation: token
  - transform: null
  
precompute_all: true
cache: true
max_cache_size: null
subsample: null
