_target_: torch.utils.data.DataLoader
_partial_: true

batch_size: 50
num_workers: ${eval:"__import__('importlib').import_module('chemtorch.utils.hydra').get_num_workers()"}
pin_memory: true
# persistent_workers: true
