defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

# LOGGING (Weight and Biases)
log: false
project_name: chemtorch
group_name: null
run_name: null

# INITIALIZATION
seed: 0

tasks: null

parameter_limit: null

runtime_args_from_dataset: null

# MODEL LOADING
load_model: false
ckpt_path: null

# PREDICTION SAVING
# Specify a single save path if only a single partition is instantiated, 
# i.e. the single task it either 'predict', 'validate', or 'test'). If null, no
# predictions will be saved.
predictions_save_path: null
# Specify a directory path to which the predictions will be saved and for 
# which partitions to save predictions if multiple partitions are instantiated, 
# during the run i.e. the task is 'fit' or tasks contain multiple tasks. If 
# null, no predictions will be saved.
predictions_save_dir: null  
# One of "train", "val", "test", "predict" or "all" for all datasets, or a list
# of any of these to specify for which datasets to save predictions. Can be 
# specified as a single string (e.g., "train") or as a list (e.g., ["train", "val"]).
# If null, no predictions will be saved.
save_predictions_for: null

# Disable Hydra's automatic logging behavior since WandB is used for logging.
hydra:
  # Prevent Hydra from creating subdirectories to store config files, logs, etc.
  output_subdir: null
  # By default, Hydra creates a timestamped directory for each run.
  # Here, we set the output directory to the current directory so that all outputs
  # like logs and checkpoints are redirected to the project root.
  run:
    dir: .