_target_: chemtorch.components.representation.token.token_representation_base.TokenRepresentationBase

defaults:
  - tokenizer: reaction_tokenizer

vocab_path: resources/vocab/uspto_1k.txt
max_sentence_length: 400
pad_token: "[PAD]"
unk_token: "[UNK]"
