_target_: chemtorch.representation.token.simple_token_representation.SimpleTokenRepresentation

defaults:
  - tokenizer: simple_tokenizer

vocab_path: resources/uspto-1k/vocab.txt
max_sentence_length: 400
pad_token: "[PAD]"
unk_token: "[UNK]"
