_target_: deepreaction.model.gnn.GNN

defaults:
  - encoder: linear_enc
  - layer_stack: layer_stack
  - layer_stack/gnn_block/gatv2_block@layer_stack.layer
  - pool: global_pool
  - head: mlp

hidden_channels: 64