_target_: chemtorch.components.model.gotennet.GotenNetChemTorchR

defaults:
  - head: mlp

n_atom_basis: 256
n_interactions: 4
n_rbf: 32
cutoff_fn:
  _target_: chemtorch.components.model.gotennet.CosineCutoff
  cutoff: 5.0
radial_basis: "expnorm"
activation: "swish"
bias_init: "zeros"
weight_init: "xavier_uniform"

max_z: 100

head:
  in_channels: ${model.n_atom_basis}
  hidden_size: ${model.n_atom_basis}
