_target_: chemtorch.components.model.gnn.gnn.GNN

defaults:
  - encoder: rwpe_and_linear_enc
  - layer_stack: layer_stack
  - layer_stack/gnn_block/gps_block@layer_stack.layer
  - pool: global_pool
  - head: mlp

hidden_channels: 128
