_target_: chemtorch.components.model.gnn.gnn.GNN

defaults:
  - encoder: linear_enc
  - layer_stack: layer_stack
  - layer_stack/gnn_block/pna_block@layer_stack.layer
  - pool: global_pool
  - head: mlp

hidden_channels: 64
layer_stack.depth: 9
