ckpt_path: null
data_pipeline:
  _target_: chemtorch.components.data_pipeline.SimpleDataPipeline
  column_mapper:
    _target_: chemtorch.components.data_pipeline.column_mapper.ColumnFilterAndRename
    label: dE0
    smiles: smiles
  data_source:
    _target_: chemtorch.components.data_pipeline.data_source.SingleCSVSource
    data_path: data/rdb7/barriers/forward/data.csv
  data_splitter:
    _target_: chemtorch.components.data_pipeline.data_splitter.RatioSplitter
    test_ratio: 0.1
    train_ratio: 0.8
    val_ratio: 0.1
dataloader:
  _partial_: true
  _target_: torch_geometric.loader.DataLoader
  batch_size: 64
  num_workers: 3
  pin_memory: true
dataloader.batch_size: 64
dataset:
  _partial_: true
  _target_: chemtorch.components.dataset.GraphDataset
  cache: true
  max_cache_size: null
  precompute_all: true
  representation:
    _target_: chemtorch.components.representation.graph.cgr.CGR
    atom_featurizer:
      _target_: chemtorch.components.representation.graph.featurizer.FeaturizerCompose
      featurizers:
      - _target_: chemtorch.components.representation.graph.featurizer.OrganicAtomicNumberOneHotFeaturizer
      - _target_: chemtorch.components.representation.graph.featurizer.AtomDegreeFeaturizer
      - _target_: chemtorch.components.representation.graph.featurizer.AtomFormalChargeFeaturizer
      - _target_: chemtorch.components.representation.graph.featurizer.AtomHCountFeaturizer
      - _target_: chemtorch.components.representation.graph.featurizer.AtomHybridizationFeaturizer
      - _target_: chemtorch.components.representation.graph.featurizer.AtomIsAromaticFeaturizer
      - _target_: chemtorch.components.representation.graph.featurizer.CentiAtomMassFeaturizer
      - _target_: chemtorch.components.representation.graph.featurizer.AtomIsInRingFeaturizer
    bond_featurizer:
      _target_: chemtorch.components.representation.graph.featurizer.FeaturizerCompose
      featurizers:
      - _target_: chemtorch.components.representation.graph.featurizer.BondTypeFeaturizer
      - _target_: chemtorch.components.representation.graph.featurizer.BondIsConjugatedFeaturizer
      - _target_: chemtorch.components.representation.graph.featurizer.BondInRingFeaturizer
    in_channel_multiplier: 2
  subsample: null
group_name: chemtorch_benchmark
load_model: false
log: true
mean: 80.0102253144654
model:
  _target_: chemtorch.components.model.gnn.gnn.GNN
  encoder:
    _target_: chemtorch.components.model.gnn.encoder.directed_edge_enc.DirectedEdgeEncoder
    in_channels: 110
    out_channels: 256
  head:
    _target_: chemtorch.components.model.mlp.MLP
    act: relu
    dropout: 0.012368200731827074
    hidden_size: 256
    in_channels: 256
    num_hidden_layers: 4
    out_channels: 1
  hidden_channels: 256
  layer_stack:
    _target_: chemtorch.components.layer.gnn_layer.dmpnn_stack.DMPNNStack
    depth: 12
    dmpnn_blocks:
      _recursive_: false
      _target_: chemtorch.components.layer.layer_stack.LayerStack
      depth: 12
      layer:
        _target_: chemtorch.components.layer.gnn_layer.DMPNNBlock
        act: relu
        dropout: 0.16713747610272822
        ffn: true
        graph_conv:
          _target_: chemtorch.components.layer.gnn_layer.DMPNNConv
          in_channels: 256
          out_channels: 256
          separate_nn: false
        hidden_channels: 256
        norm: None
        residual: true
    edge_to_node_embedding:
      _target_: chemtorch.components.layer.gnn_layer.dmpnn_stack.EdgeToNodeEmbedding
      embedding_size: 256
      num_node_features: 88
  pool:
    _target_: chemtorch.components.model.gnn.pool.pool.GlobalPool
    aggr: add
model.head.dropout: 0.012368200731827074
model.head.num_hidden_layers: 4
model.hidden_channels: 256
model.layer_stack.depth: 12
model.layer_stack.dmpnn_blocks.layer.dropout: 0.16713747610272822
model.layer_stack.dmpnn_blocks.layer.norm: null
name: cgr_dmpnn
num_edge_features: 22
num_node_features: 88
parameter_limit: null
prediction_save_path: null
predictions_save_dir: predictions/chemtorch_paper/rdb7_model_benchmark/cgr_dmpnn/seed_${seed}_${now:%Y-%m-%d_%H-%M-%S}
save_predictions_for: [train, test]
project_name: chemtorch
routine:
  _convert_: object
  _partial_: true
  _target_: chemtorch.core.routine.RegressionRoutine
  loss:
    _target_: torch.nn.modules.loss.MSELoss
  lr_scheduler:
    frequency: 1
    interval: epoch
    scheduler:
      _partial_: true
      _target_: chemtorch.core.scheduler.cosine_with_warmup_lr.CosineWithWarmupLR
      end_factor: 1.0
      eta_min: 0.0
      num_training_steps: 100
      num_warmup_steps: 10
      start_factor: 1.0e-06
  metrics:
    test:
      _target_: torchmetrics.MetricCollection
      metrics:
        mae:
          _target_: torchmetrics.MeanAbsoluteError
        rmse:
          _target_: torchmetrics.MeanSquaredError
          squared: false
    train:
      _target_: torchmetrics.MetricCollection
      metrics:
        rmse:
          _target_: torchmetrics.MeanSquaredError
          squared: false
    val:
      _target_: torchmetrics.MetricCollection
      metrics:
        rmse:
          _target_: torchmetrics.MeanSquaredError
          squared: false
  optimizer:
    _partial_: true
    _target_: torch.optim.AdamW
    amsgrad: false
    betas:
    - 0.9
    - 0.999
    capturable: false
    eps: 1.0e-08
    foreach: null
    lr: 0.0005682742759208353
    maximize: false
    weight_decay: 0.0006307405281515754
  standardizer:
    _target_: chemtorch.utils.Standardizer
    mean: 80.0102253144654
    std: 21.684054853890036
routine.optimizer.lr: 0.0005682742759208353
routine.optimizer.weight_decay: 0.0006307405281515754
run_name: cgr_dmpnn
runtime_args_from_dataset:
- num_node_features
- num_edge_features
- mean
- std
seed: 0
std: 21.684054853890036
tasks:
- fit
- test
trainer:
  _target_: lightning.Trainer
  accelerator: auto
  callbacks:
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    min_delta: 0.01
    mode: min
    monitor: val_loss_epoch
    patience: 30
  default_root_dir: ./lightning_logs
  gradient_clip_val: 1.0
  logger:
    _target_: lightning.pytorch.loggers.WandbLogger
  max_epochs: 100
  enable_checkpointing: true
  checkpoint_callback:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${trainer.default_root_dir}/chemtorch_paper/rdb7_model_benchmark/cgr_dmpnn/seed_${seed}_${now:%Y-%m-%d_%H-%M-%S}/checkpoints
    monitor: val_loss
    save_top_k: 1
    save_last: true
