_target_: chemtorch.components.preprocessing.featurizer.FeaturizerCompose

featurizers:
  - _target_: chemtorch.components.preprocessing.featurizer.OrganicAtomicNumberOneHotFeaturizer
  - _target_: chemtorch.components.preprocessing.featurizer.AtomDegreeFeaturizer
  - _target_: chemtorch.components.preprocessing.featurizer.AtomFormalChargeFeaturizer
  - _target_: chemtorch.components.preprocessing.featurizer.AtomHCountFeaturizer
  - _target_: chemtorch.components.preprocessing.featurizer.AtomHybridizationFeaturizer
  - _target_: chemtorch.components.preprocessing.featurizer.AtomIsAromaticFeaturizer
  - _target_: chemtorch.components.preprocessing.featurizer.CentiAtomMassFeaturizer
  - _target_: chemtorch.components.preprocessing.featurizer.AtomIsInRingFeaturizer
