_target_: chemtorch.components.representation.token.tokenizer.molecule_tokenizer.substructure_tokenizer.SubstructureTokenizer
radii: [0, 1, 2]
vocab_path: resources/substruc_vocab.txt
pad_token: "[PAD]"
unk_token: "[UNK]"