_target_: torch.optim.lr_scheduler.LambdaLR
_partial_: true
lr_lambda:
  _target_: chemtorch.scheduler.graphgps_cosine_with_warmup_lr.get_cosine_scheduler_with_warmup
  num_warmup_steps: 10
  num_training_steps: ${routine.epochs}
  num_cycles: 0.5
