_target_: chemtorch.data_ingestor.SimpleDataIngestor

defaults:
  - data_source: pre_split_csv_source
  - column_mapper: column_filter_and_rename
  - data_splitter: null

data_source:
  data_folder: "chemtorch_datasets/data/cycloaddition/barriers" # example data folder

column_mapper:
  column_mapping:
    smiles: "rxn_smiles"
    label: "G_act"
