_target_: chemtorch.data_ingestor.SimpleDataIngestor

defaults:
  - data_source: pre_split_csv_source
  - column_mapper: column_filter_and_rename
  - data_splitter: null

data_source:
  data_folder: "data/rdb7"

column_mapper:
  column_mapping:
    smiles: "smiles"
    label: "dE0"
