_target_: deepreaction.data_ingestor.SimpleDataIngestor

defaults:
  - data_source: single_csv_source
  - column_mapper: column_filter_and_rename
  - data_splitter: ratio_splitter

data_source:
  data_path: "data/sn2/barriers/data.csv"
  
column_mapper:
  column_mapping:
    smiles: "AAM"
    label: "ea"

data_splitter:
  train_ratio: 0.9
  val_ratio: 0.05
  test_ratio: 0.05
