_target_: deepreaction.data_ingestor.SimpleDataIngestor

defaults:
  - data_source: pre_split_csv
  - column_mapper: column_filter_and_rename
  - data_splitter: null

data_source:
  data_folder: "data/uspto_1k"
  
column_mapper:
  column_mapping:
    smiles: "reaction"
    label: "labels"
